### ISSUE TITLE
Always "HSM error: MemoryError" after accidentally deleting the first key

### ISSUE THREAD

**Issue by yulidai** [tendermint/yubihsm-rs#206]
Error "HSM error: MemoryError" occured after accidentally deleting the first key:
```
client.delete_object(1, object::Type::AuthenticationKey);
```

Can't access it by `Client`, is it broken? if not, how can i fix it?  T.T

**Comment by tarcieri** [comment]
It sounds like you deleted the master authentication key. If that’s what you used to authenticate, you now no longer have any authentication keys and all you can do is a factory reset.
