### ISSUE TITLE
libusb unmaintained

### ISSUE THREAD

**Issue by flukejones** [tendermint/yubihsm-rs#230]
Or at least appears to be. There is a small issue with it currently which hasn't had a resolution in the repo, and so it has been forked to `rusb`.
Check out the issue [here](https://github.com/a1ien/rusb/pull/2)

**Comment by tarcieri** [comment]
Thanks. This is definitely something we've been concerned with although we haven't had an alternative in the past. `rusb` looks interesting.

**Comment by flukejones** [comment]
As I understand it, `rusb` is a fork of `libusb` to fix a few issues.
