### ISSUE TITLE
put_auth_key missing delegated_capabilities

### ISSUE THREAD

**Issue by archaelus** [tendermint/yubihsm-rs#68]
The put auth key function @ put_auth_key.rs:23 is missing a delegated capabilities parameter, which is specified in [https://developers.yubico.com/YubiHSM2/Commands/Put_Authkey.html](https://developers.yubico.com/YubiHSM2/Commands/Put_Authkey.html) as 8 bytes before the key material.

I think this needs to be changed to something along the lines of put_wrap_key.

**Comment by tarcieri** [comment]
I so happen to be in the process of rewriting much of the auth key code right now in a local branch I haven't published yet, but I noticed this as well while writing an integration test for `put_auth_key` and have already fixed it. I'll push up my branch as a PR shortly (i.e. later today).

**Comment by archaelus** [comment]
:+1:

**Comment by tarcieri** [comment]
Fixed in 313b46e
