### ISSUE TITLE
Can't get_object_info on default AuthKey

### ISSUE THREAD

**Issue by archaelus** [tendermint/yubihsm-rs#70]
The default AuthKey (id:1) on a reset YubiHSM2 has capabilities and delegated_capabilities of 18446744073709551615 (all 1s). This can't be decoded by Capability/deserialize as it specifies invalid bitflags (guessing).

The bytes for the default authkey are: `[255, 255, 255, 255, 255, 255, 255, 255, 0, 1, 0, 40, 255, 255, 2, 38, 0, 2, 68, 69, 70, 65, 85, 76, 84, 32, 65, 85, 84, 72, 75, 69, 89, 32, 67, 72, 65, 78, 71, 69, 32, 84, 72, 73, 83, 32, 65, 83, 65, 80, 0, 192, 255, 238, 192, 255, 238, 1, 255, 255, 255, 255, 255, 255, 255, 255]`.

**Comment by tarcieri** [comment]
Interesting. I think the simplest solution would be to make placeholder capabilities for the presently unassigned values (e.g. `const UNKNOWN_0x16 = 0x16`) in the `Capability` `bitflags!`

**Comment by archaelus** [comment]
that sounds doable.
